-- ALTER TABLE ROLE_Func DROP CONSTRAINT FKROLE_Func244238;
-- ALTER TABLE ROLE_Func DROP CONSTRAINT FKROLE_Func638921;
-- ALTER TABLE User_ROLE DROP CONSTRAINT FKUser_ROLE307659;
-- ALTER TABLE User_ROLE DROP CONSTRAINT FKUser_ROLE102814;

DROP TABLE ROLE IF EXISTS;
DROP TABLE Account IF EXISTS;
DROP TABLE Func IF EXISTS;
DROP TABLE ROLE_Func IF EXISTS;
DROP TABLE User_ROLE IF EXISTS;
CREATE TABLE ROLE (ID INT NOT NULL AUTO_INCREMENT, role_desc varchar(255), role_code varchar(20), PRIMARY KEY (ID));
CREATE TABLE Account (ID INT NOT NULL AUTO_INCREMENT, account_name varchar(255), user_real_name varchar(255), encrypt_passwd varchar(255), activate bit, PRIMARY KEY (ID));
CREATE TABLE Func (ID INT NOT NULL AUTO_INCREMENT, func_code varchar(255), func_name varchar(255), parent_id int, PRIMARY KEY (ID));
CREATE TABLE ROLE_Func (role_id int NOT NULL, fun_id int NOT NULL, PRIMARY KEY (role_id, fun_id));
CREATE TABLE User_ROLE (user_id int NOT NULL, role_id int NOT NULL, PRIMARY KEY (user_id, role_id));
ALTER TABLE ROLE_Func ADD CONSTRAINT FKROLE_Func244238 FOREIGN KEY (role_id) REFERENCES ROLE (id);
ALTER TABLE ROLE_Func ADD CONSTRAINT FKROLE_Func638921 FOREIGN KEY (fun_id) REFERENCES Func (id);
ALTER TABLE User_ROLE ADD CONSTRAINT FKUser_ROLE307659 FOREIGN KEY (user_id) REFERENCES Account (id);
ALTER TABLE User_ROLE ADD CONSTRAINT FKUser_ROLE102814 FOREIGN KEY (role_id) REFERENCES ROLE (id);